- project:
    templates:
      - openstack-python3-charm-jobs
      - openstack-cover-jobs
    check:
      jobs:
        - charmbuild
    vars:
      charmbuild_charmcraft_channel: 3.x/stable
      charm_build_name: nova-compute
